# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '网络监听demo2' do
  pod 'AFNetworking', '~> 3.1.0'

  target '网络监听demo2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '网络监听demo2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
